### PR TITLE
chore: upgrade to node v18

### PR DESCRIPTION
**Pull request by ecshreve**
## What does this do?
upgrade to node version 18

## How was it tested?
localhost / ci

## Is there a Github issue this is resolving?
no

## Was any impacted documentation updated to reflect this change?
no

## Here's a fun image for your troubles
random photo - update me

### CODE REVIEW

**Review by bagelbits — COMMENTED** [review]
You'll want to update the versions here too:
* https://github.com/5e-bits/5e-srd-api/blob/main/Dockerfile
* https://github.com/5e-bits/5e-srd-api/blob/main/.nvmrc

**Comment by bagelbits** [comment]
@ecshreve When you get a chance, can you rebase as well? I just merged in a change so I can deploy review apps to test this kind of thing.

**Comment by ecshreve** [comment]
> @ecshreve When you get a chance, can you rebase as well? I just merged in a change so I can deploy review apps to test this kind of thing.

@bagelbits just got back to this PR. rebased and updated the two places you mentioned so should be ready to try out as a review app shorly!

**Comment by bagelbits** [comment]
@ecshreve Fully deployed!

**Review by bagelbits — APPROVED** [review]

**Comment by ecshreve** [comment]
awesome! i might poke around and look at doing little more dependency cleanup / version updates so glad the review app flow worked to test this one

**Pull request merged**
